language: scala

jdk: openjdk13

services:
  - docker

scala:
  - 2.13.10

before_install:
  - sbt ++"$TRAVIS_SCALA_VERSION" publishLocalAll
  - docker-compose up -d

script:
  - sbt ++"$TRAVIS_SCALA_VERSION" test && sbt ++"$TRAVIS_SCALA_VERSION" it:test