services:

  order:
    image: order:latest
    ports:
      - "8080:8080"
    environment:
      - ORDER_SERVER_PORT=8080

  customer:
    image: customer:latest
    ports:
      - "8081:8081"
    environment:
      - CUSTOMER_SERVER_PORT=8081
      - ORDER_SERVER_PORT=8080
      - ORDER_SERVER_HOST=http://order