addSbtPlugin("com.github.sbt"            % "sbt-native-packager"       % "1.9.11")
addSbtPlugin("org.scalameta"             % "sbt-scalafmt"              % "2.4.6")
addSbtPlugin("com.github.cb372"          % "sbt-explicit-dependencies" % "0.2.16")
addSbtPlugin("ch.epfl.scala"             % "sbt-scalafix"              % "0.10.4")
addSbtPlugin("org.wartremover"           % "sbt-wartremover"           % "3.0.6")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"              % "0.4.1")
